### ISSUE TITLE
change-case is added as a devDependency but is used at runtime

### ISSUE THREAD

**Issue by klarstrup** [date-fns/date-fns-upgrade-codemod#3]
https://github.com/date-fns/date-fns-upgrade-codemod/blob/2e7577146f284e53037c5925635c1c39574766a4/package.json#L24

**Comment by dkozickis** [comment]
Uh... Will release fix today :( 

Thank you!

**Comment by dkozickis** [comment]
Shipped `1.0.0-beta.2` 🙇
